package com.tedu.teamserver.controller;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : team
//  @ File Name : UserTeamRelationController.java
//  @ Date : 2022/7/6
//  @ Author :
//
//
import com.tedu.teamserver.pojo.ServerResult.ServerResult;
import com.tedu.teamserver.pojo.UserTeamRelation.UserTeamRelationDAO;
import com.tedu.teamserver.pojo.UserTeamRelation.UserTeamRelationInsertDTO;
import com.tedu.teamserver.pojo.UserTeamRelation.UserTeamRelationVO;
import com.tedu.teamserver.service.UserTeamRelationService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

//http://localhost:9003/doc.html
@RestController
@CrossOrigin
public class UserTeamRelationController {
    //自动获取服务层的对象
    @Autowired
    UserTeamRelationService userTeamRelationService;

    @RequestMapping("/userTeamRelation/selectJoin")
    public ServerResult selectJoin(Integer id){
        List<UserTeamRelationVO> voList = userTeamRelationService.selectJoin(id);
        return new ServerResult(0,"查询成功",voList);
    }

    @RequestMapping("/userTeamRelation/selectLaunch")
    public ServerResult selectLaunch(Integer id){
        List<UserTeamRelationVO> voList = userTeamRelationService.selectLaunch(id);
        return new ServerResult(0,"查询成功",voList);
    }

    @RequestMapping("/userTeamRelation/selectById")
    public ServerResult selectById(Integer id) {
        UserTeamRelationDAO userTeamRelationDAO = userTeamRelationService.selectById(id);
        return new ServerResult(0,"成功",userTeamRelationDAO);
    }

    //需要查询到团队名吗
    @RequestMapping("/userTeamRelation/selectByUserId")
    public ServerResult selectByUserId(Integer id) {
        List<UserTeamRelationDAO> list = userTeamRelationService.selectByUserId(id);
        return new ServerResult(0,"成功",list);
    }

    //失败状态码：按照数据库中表的位置，user_team_relation是第六张表，故命名为601等。
    @RequestMapping("/userTeamRelation/insert")
    public ServerResult insert(UserTeamRelationInsertDTO userTeamRelationInsertDTO) {
        boolean isSuccess = userTeamRelationService.insert(userTeamRelationInsertDTO);
        if(isSuccess){
            return new ServerResult(0,"成功",null);
        }else{
            return new ServerResult(601,"添加失败",null);
        }
    }
}
