package com.tedu.teamserver.mapper;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : team
//  @ File Name : UserTeamRelationMapper.java
//  @ Date : 2022/7/6
//  @ Author : 
//
//

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.tedu.teamserver.pojo.UserTeamRelation.UserTeamRelationDAO;
import org.apache.ibatis.annotations.Mapper;

/**
 * Function:用来在网页上显示的对象
 * Time:2022/7/6
 */

@Mapper //mybatis-plus为接口创建实现类，再创建对象，把对象放在spring容器中，业务层通过autowired就能取到对象

public interface UserTeamRelationMapper extends BaseMapper<UserTeamRelationDAO> {
}
