package com.tedu.teamserver.service;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : team
//  @ File Name : UserTeamRelationService.java
//  @ Date : 2022/7/6
//  @ Author : 
//
//

import com.tedu.teamserver.pojo.UserTeamRelation.UserTeamRelationDAO;
import com.tedu.teamserver.pojo.UserTeamRelation.UserTeamRelationInsertDTO;
import com.tedu.teamserver.pojo.UserTeamRelation.UserTeamRelationVO;

import java.util.List;

public interface UserTeamRelationService {

	public UserTeamRelationDAO selectById(Integer id);

	public List<UserTeamRelationDAO> selectByUserId(Integer id);

	public List<UserTeamRelationVO> selectJoin(Integer id);

	public List<UserTeamRelationVO> selectLaunch(Integer id);

	public boolean insert(UserTeamRelationInsertDTO userTeamRelationInsertDTO);
}
