package com.tedu.teamserver.pojo.UserTeamRelation;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : team
//  @ File Name : UserTeamRelationDAO.java
//  @ Date : 2022/7/6
//  @ Author : 
//
//

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Description:用户组队表，记录用户的userId和加入的队伍teamId。joinId为自增主键
 * Time:2022/7/6
 */

@TableName("user_team_relation")
public class UserTeamRelationDAO {
	@TableId(type = IdType.AUTO)
	public Integer joinId;
	public Integer userId;
	public Integer teamId;

	public Integer getJoinId() {
		return joinId;
	}

	public void setJoinId(Integer joinId) {
		this.joinId = joinId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getTeamId() {
		return teamId;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}
}
